### PR TITLE
windowsdesktop-runtime-31-np: Add version 3.1.25

### PR DESCRIPTION
**Pull request by Ryanjiena**
* windowsdesktop-runtime-31-np: Add to version 3.1.25 [JaimeZeng] G
o Merge branch 'master' of github.com:Ryanjiena/Meta [JaimeZeng] G

 - [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ryanjiena** [comment]
$comment

**Comment by JaimeZeng** [comment]
All changes look good.

Wait for review from human collaborators.
### windowsdesktop-runtime-31-np

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate
- [x] Autoupdate Hash Extraction

**Comment by Ryanjiena** [comment]
fix #354

**Review by JaimeZeng — APPROVED** [review]

**Pull request merged**
