### PR TITLE
windowsdesktop-runtime-6: Add version 6.0.5

### PR DESCRIPTION
**Pull request by Ryanjiena**
* windowsdesktop-runtime-6: Add to version 6.0.5 [JaimeZeng] G
o Merge branch 'master' of github.com:Ryanjiena/Meta [JaimeZeng] G

 - [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by JaimeZeng** [comment]
[Your changes do not pass checks.](https://github.com/Ash258/Scoop-GithubActions/wiki/Pull-Request-Checks)
### windowsdesktop-runtime-6

- [x] Description
- [x] License
- [ ] Hashes
- [x] Checkver
- [x] Autoupdate
- [x] Autoupdate Hash Extraction

**Comment by JaimeZeng** [comment]
All changes look good.

Wait for review from human collaborators.
### windowsdesktop-runtime-6

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate
- [x] Autoupdate Hash Extraction

**Comment by Ryanjiena** [comment]
fix #354

**Review by JaimeZeng — APPROVED** [review]

**Pull request merged**
